### ISSUE TITLE
Could you please make Unreal DevOP's Dynamic Additive Overlay replicated?

### ISSUE THREAD

**Issue by kuyin** [cenairaclub/motionmatchingreplicated#1]
This guy called Unreal [Unreal DevOP](https://www.youtube.com/@unrealdevop) made a version with Dynamic Additive Overlay. [Video](https://www.youtube.com/watch?v=POf6sTecfcE) [ProjectDownload](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbVVyNFE2V21VSDRRdVVrVl9MaEtiX3BqNmJBd3xBQ3Jtc0tsOVVvYkpaVUthR1pPVThzUHlFOXJXUWxUenlleTFwa1lkWW1wOGVoWmVHdFJJWnVOLUYzTnVhN1phVjhpTlBnYjhRLS1uY1lVM1l0R2ZLOVZKTXRxZ0NxRXU2c1pSOTBPS3NrS2xKRWJLT2ZDSkVaZw&q=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1AOV5LoecijaobCvC8IblW-HTkfpIgAI9%2Fview%3Fusp%3Dsharing&v=POf6sTecfcE)

Could you guys talk and cooperate? That will be cool.

**Comment by UmutFarukDilli** [comment]
İ will entegrate it to my repository, thanks! 😄 I dont need to ask him actually.

**Comment by UmutFarukDilli** [comment]
Done.
https://www.youtube.com/watch?v=cv2pnYxBfa0

**Comment by kuyin** [comment]
Hello [UnrealDevOP](https://www.youtube.com/@unrealdevop) update his [Overlay](https://drive.google.com/file/d/1AOV5LoecijaobCvC8IblW-HTkfpIgAI9/view) project into 1.07. Could you please check and merge it?

**Comment by UmutFarukDilli** [comment]
I see that very little has changed in the project, I'll check it out when it changes a little more.
