### ISSUE TITLE
New Travel Bug

### ISSUE THREAD

**Issue by kuyin** [cenairaclub/motionmatchingreplicated#2]
I found a bug when you climbing the 2.5m block. The character will be stuck on the halfway and drop down in the run mode. But in walking mode it works fine.
Please check it out.
![image](https://github.com/cenairaclub/motionmatchingreplicated/assets/7321275/ce9809cf-5ca9-421e-8746-72c6e2a52722)

**Comment by kuyin** [comment]
And here is a reference working good you can reference.
https://github.com/MrTapa/DynamicLedgeDetection

**Comment by UmutFarukDilli** [comment]
I'm working on it, thanks!

**Comment by UmutFarukDilli** [comment]
> And here is a reference working good you can reference. https://github.com/MrTapa/DynamicLedgeDetection

Im changing the system with this, 😄 But its little big buggy, im solving the bugs then publishing.

**Comment by UmutFarukDilli** [comment]
Done.

**Comment by kuyin** [comment]
By the way， did you use the complex trace when do capsule tracing？ It will help sometimes.

**Comment by UmutFarukDilli** [comment]
yeap, the MrTapa used complex. I entegrated it in another component, and thats it.
![image](https://github.com/cenairaclub/motionmatchingreplicated/assets/14151235/126767c4-e097-4662-b2ae-ef91d602648b)

**Comment by UmutFarukDilli** [comment]
I removed my 11 hours work :D Because tapa's is better

**Comment by UmutFarukDilli** [comment]
Oh, i guess the ORIGINAL TRACES that we use are not complex trace.

**Comment by kuyin** [comment]
> Oh, i guess the ORIGINAL TRACES that we use are not complex trace.

Yeah that's what i mean

**Comment by UmutFarukDilli** [comment]
Actually we are not doing Hand IK, so, i dont think its necessery at the moment. If you will upgrade yourself, you can always change the variables, functions etc 😄
