### ISSUE TITLE
Movement Glitch when changing direction

### ISSUE THREAD

**Issue by Helltears** [cenairaclub/motionmatchingreplicated#3]
Hi! i'm having issues with the way the character moves on the viewport when changing directions. How can this be fixed?

**Comment by Helltears** [comment]
https://github.com/cenairaclub/motionmatchingreplicated/assets/98957695/a86f35f7-010d-4305-9ca3-4ff6519ac856

video to explain, also i have smooth sync on and i don't want the character to strafe

**Comment by Helltears** [comment]
looks like the control rotation is acting weird


https://github.com/cenairaclub/motionmatchingreplicated/assets/98957695/8028d127-9879-4560-b743-eb435c89e87b

**Comment by UmutFarukDilli** [comment]
Thanks for the information, i will handle it!

**Comment by UmutFarukDilli** [comment]
Smooth Sync makes rotation changes smoother, and thats the problem, i disabled the rotation smoothing. And im trying to replicates rotation manually.
![image](https://github.com/cenairaclub/motionmatchingreplicated/assets/14151235/5cf6d8ee-2e23-402a-a6c6-a7479b827ae8)

**Comment by UmutFarukDilli** [comment]
nope, i turned on it again, the problem was Rotation Rate
I changed it to 540 from -1

**Comment by Helltears** [comment]
Doesn't work, my rotation rate was already on -1 :/

**Comment by UmutFarukDilli** [comment]
![image](https://github.com/cenairaclub/motionmatchingreplicated/assets/14151235/f0a32054-ab05-4bd6-905d-e67c55cd933c)
Go to this function and change the Z value to 540

**Comment by Helltears** [comment]
thanks! seems to be working better but now the legs don't follow the movement as well :/

**Comment by Helltears** [comment]
it looks like sometimes the animation of the legs plays in reverse and the legs don't always follow the right direction on replication (upper body always goes the right way but legs don't)

**Comment by UmutFarukDilli** [comment]
I will look at it soon

**Comment by Helltears** [comment]
alright thanks!

**Comment by UmutFarukDilli** [comment]
I just looked, and cant see a problem, can you share a video pls

**Comment by Helltears** [comment]
Hi here is a video with the problems i'm noticing, rotation setting on the last 20 seconds. happens most noticeably on the walking state while not strafing (orient rotation to movement is true and controller desired rotation is false

https://youtu.be/Azsp9jn7W8U?si=vReA2OsAr06KggLY

**Comment by UmutFarukDilli** [comment]
Can you check is Network Emulation is OFF in your project?

**Comment by Helltears** [comment]
> Can you check is Network Emulation is OFF in your project?

turned it off, don't know why it was on but it seems to have fixed pretty much all the issues. Thanks!

**Comment by UmutFarukDilli** [comment]
İt was on because i forgot it 😄 😄
