### ISSUE TITLE
Simulated proxy jitters or looks like it wants to rotate, when autonomous proxy rotates its camera.  Would expect to see no reaction from a simulated proxy.

### ISSUE THREAD

**Issue by moosah-edge** [cenairaclub/motionmatchingreplicated#5]
For some reason simulated proxies are attempting to rotate when the autonomous proxy rotates their camera when smooth sync's sync rotation Z is enabled.

https://github.com/user-attachments/assets/be7ad557-d0ce-409a-b0b1-4a653f9e04f7

**Comment by UmutFarukDilli** [comment]
Check the network emulation, make it Turned Off

**Comment by moosah-edge** [comment]
Sorry, that was with network emulation turned off

**Comment by UmutFarukDilli** [comment]
i guess the problem is  "Wants to strafe" variable is not syncned
