### ISSUE TITLE
Duplicated Character blueprint does't work 

### ISSUE THREAD

**Issue by lyc233nb** [cenairaclub/motionmatchingreplicated#8]
Hi, you have really done a great job. However, I found that whenever i duplicate the character blurpeint from the CBP_SandboxCharacter. The duplicated character blueprint dose not play any animations.

**Comment by UmutFarukDilli** [comment]
check the references and Cast To's.
for example in Anim bp.

**Comment by lyc233nb** [comment]
got it. Thank u very much!!!
